server:
  port: 7085
spring:
  application:
    name: zhao-seata-order
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.8.128:8848
        register-enabled: true
        namespace: 0a825456-b821-4782-8e15-c2a5e8fee4ff
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.128:3306/order?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: seata-server
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: 0a825456-b821-4782-8e15-c2a5e8fee4ff
      serverAddr: 192.168.8.128:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      namespace: 0a825456-b821-4782-8e15-c2a5e8fee4ff
      application: seata-server
      server-addr: 192.168.8.128:8848
      userName: "nacos"
      password: "nacos"